[project]
name = "triton-gpt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest>=9.0.1",
    "torch>=2.9.1",
    "triton>=3.5.1",
]
